# -*- coding: utf-8 -*-
"""Fixture loaders for the regression tests.

They follow the same reading rules the original validation scripts used.
If the rules drift, the expectations stop reproducing — so the way of
reading is itself under test.
"""
from __future__ import annotations

import os

from core.dataset import build
from core.importer import apply_profile, group_rows, preview, read_csv, read_xlsx
from core.profile import ColumnMap, ImportProfile
from core.project import Project
from core.spec import ObjSpec, VarSpec

DATA = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")

# The three public datasets. The log setting changes σw and D
# (mind the regression table when touching it).
EXTERNAL = {
    "p3ht":       ("p3ht.csv",       "Conductivity (measured) (S/cm)", True),
    "perovskite": ("perovskite.csv", "Instability index",              True),
    "agnp":       ("agnp.csv",       "loss",                           False),
}


def synthetic():
    """synthetic_raman.xlsx — column A power · B dwell · E response.

    Generated by tests/data/make_synthetic.py (seed pinned). It mirrors the
    structure of the lab spreadsheet the original study anchored on: conditions
    written on every row, blank-cell inheritance still exercised (§6-2), and
    the 10 all-zero conditions excluded as destroyed samples (F-05).
    """
    rows = read_xlsx(os.path.join(DATA, "synthetic_raman.xlsx"))[1:]
    groups, _ = group_rows(rows, ["A", "B"], "E", inherit=True)
    inputs = [VarSpec("power", "W", "continuous", 150, 190),
              VarSpec("dwell", "s", "integer", 3, 7)]
    obj = ObjSpec("G/D ratio", "a.u.", "max", log=False)
    return build(groups, inputs, obj, exclude_zero=True)


def synthetic_profile() -> ImportProfile:
    """The reading rules for the synthetic spreadsheet — A power · B dwell · E response."""
    cols = [ColumnMap("A", "input", "power", "W", "continuous"),
            ColumnMap("B", "input", "dwell", "s", "integer"),
            ColumnMap("C", "ignore"), ColumnMap("D", "ignore"),
            ColumnMap("E", "response", "G/D ratio", "a.u.", "continuous"),
            ColumnMap("F", "ignore")]
    return ImportProfile(kind="xlsx", sheet=1, header_row=1, columns=cols,
                         inherit_blank=True, exclude_zero=True)


def synthetic_project() -> Project:
    """The same spreadsheet as the Project the GUI tests open. It locks — ② learnability FAIL."""
    path = os.path.join(DATA, "synthetic_raman.xlsx")
    keys, rows = preview(path, "xlsx", 1, limit=10 ** 9)
    prof = synthetic_profile()
    prof.columns = [c for c in prof.columns if c.key in keys]
    ms, _ = apply_profile(rows, prof)
    return Project(name="Synthetic G/D",
                   inputs=[VarSpec("power", "W", "continuous", 150, 190, step=10.0),
                           VarSpec("dwell", "s", "integer", 3, 7)],
                   objective=ObjSpec("G/D ratio", "a.u.", "max"),
                   budget_total=40, measurements=[dict(m) for m in ms],
                   exclude_zero=True, import_profile=prof)


def external(name: str):
    fn, resp, log = EXTERNAL[name]
    rows = read_csv(os.path.join(DATA, fn))
    cols = [c for c in rows[0] if c != resp]
    groups, _ = group_rows(rows, cols, resp, inherit=False)
    inputs = [VarSpec(c, "", "continuous", 0.0, 1.0) for c in cols]
    obj = ObjSpec(resp, "", "max", log=log)
    return build(groups, inputs, obj)
